### ISSUE TITLE
Oog.jar no longer available at link

### ISSUE THREAD

**Issue by WShorrock** [AuReMe/metage2metabo#14]
the Oog.jar file is no longer available a the link provided in the documentation.

**Comment by cfrioux** [comment]
Hi, thank you for letting us now. Indeed, the developpers just recently removed their software from the [website](https://tu-dresden.de/cmcb/biotec/forschungsgruppen/schroeder/software). We are working on a alternative. If you need the file to perform some analyses in the meantime, you can contact us.

**Comment by WShorrock** [comment]
Thanks for the quick response. We would like to begin preforming analysis so having the file would be extremely helpful. Where can I reach out to you to possibly obtain the .jar?

**Comment by cfrioux** [comment]
[firstname].[lastname]@inria.fr 
with [firstname] = clemence and [lastname] = frioux

**Comment by cfrioux** [comment]
Data is now available in [M2M repository](https://github.com/AuReMe/metage2metabo/tree/master/external_dependencies)
