### ISSUE TITLE
metabolic objective

### ISSUE THREAD

**Issue by choon-sim** [AuReMe/metage2metabo#15]
Hi, I am new to metage2metabo. It looks like a great tool.

I have a general question. Can the metabolic objective be modified to subset on only certain classes of metabolites, for example, vitamins as the cooperation potential?

**Comment by cfrioux** [comment]
Hi Choon-Sim,

The metabolic objective can be customized as long as it contains metabolites that belong to the metabolic networks (i.e. from the same database). So you can definitely reduce the cooperation potential by selecting only the vitamins inside. Unfortunately you have to do it manually. 
To do so, you have to retrieve the file `community_analysis/targets.sbml`, modifiy it by removing the compounds you are not interested in, and run the command (`m2m mincom` [for instance](https://metage2metabo.readthedocs.io/en/latest/command.html#m2m-mincom)) with the `-t` argument. 

The full length results will be stored in a [json file](https://metage2metabo.readthedocs.io/en/latest/output.html#mincom-json).

Let me know if I can help you more

**Comment by choon-sim** [comment]
Hi @cfrioux 
It is helpful, thank you so much.

Choon
