### ISSUE TITLE
Create a list of targets for the content of the community metabolic potential

### ISSUE THREAD

**Issue by cfrioux** [AuReMe/metage2metabo#21]
An interesting analysis can be to select minimal communities suitable to sustain the producibility of all compounds the community can produce. This consists in building a set of targets consisting of the metabolites in the community scope (community metabolic potential).

An easy solution can be to create a SBML file containing compounds occurring in the community scope (`community_analysis/comm_scopes.json`).

**Comment by alsmadin01** [comment]
Hi @cfrioux, Hi @ArnaudBelcour,

This would be great! When will this option become available?

Best regards,

Noor Alsmadi

**Comment by ArnaudBelcour** [comment]
Added in #61.
