### ISSUE TITLE
CRITICAL:metage2metabo.m2m.reconstruction:Something went wrong running Pathway Tools. See the log file in /home/chencong/output3/pgdb_log/log_error.txt

### ISSUE THREAD

**Issue by ChenCongZ** [AuReMe/metage2metabo#46]
Hi @cfrioux,
It alerted me to this problem when I used the recon pipeline.

![Screenshot from 2022-11-26 15-27-49](https://user-images.githubusercontent.com/98649346/204077529-30e6f24c-98cd-412d-b645-290e5d12bf82.png)

**Comment by cfrioux** [comment]
Hi. It says there is no pgdb ID for fatty acid oxydation in taxon_id.tsv.
So this is what you should fix.

**Comment by ChenCongZ** [comment]
Hi @cfrioux,
Thank you!
I fix the problem, but I encountered a problem of Frame name "ESCHERICHIA COLI K12 MG1655" contains the illegal character"
However, I didn't find the root cause of this issue.
![Screenshot from 2022-11-26 19-50-17](https://user-images.githubusercontent.com/98649346/204087901-378dc831-5e26-42bb-a78e-04988e896396.png)

**Comment by cfrioux** [comment]
The error says that the space is a problem. Try removing the spaces?

**Comment by ChenCongZ** [comment]
Hi @cfrioux,
Thank you!
I apologize for time zone issues.
I will pay attention to this issue later.  I'm trying to run my data and test data and having this issue.
![Screenshot from 2022-11-27 09-20-45](https://user-images.githubusercontent.com/98649346/204115158-07b38613-6130-4b85-bbde-f64250d3dd92.png)
![Screenshot from 2022-11-26 21-25-21](https://user-images.githubusercontent.com/98649346/204115164-01f7cf1f-f945-473f-8750-8eecb909bdfd.png)

**Comment by ChenCongZ** [comment]
Hi @cfrioux, Hi @ArnaudBelcour,
Thank you for your help.
I have solved the problems I encountered before, but I didn't see this function when I created the seed file ( from metabolites file (.txt) to seed file (.sbml)). Can you teach me some command lines about it?
![QQ截图20221201203136](https://user-images.githubusercontent.com/98649346/205054689-0828ad22-2fe0-4360-953c-c2e02e18b53e.png)

**Comment by cfrioux** [comment]
The command line is in the screenshot you just attached, together with the input file structure. 
If you solved your problems, I'll close the issue.
