### ISSUE TITLE
Install metage2metabo problem

### ISSUE THREAD

**Issue by LiZhihua1982** [AuReMe/metage2metabo#50]
Installing collected packages: immutables, contextvars, sniffio, idna, dataclasses, six, rfc3986, mpmath, h11, certifi, anyio, sympy, swiglpk, ruamel.yaml.clib, pytz, python-dateutil, pygments, numpy, httpcore, commonmark, charset-normalizer, async-generator, simplejson, ruamel.yaml, rich, python-libsbml, pyfaidx, pydantic, pandas, optlang, importlib-resources, httpx, future, diskcache, depinfo, argh, argcomplete, appdirs, lxml, gffutils, cobra, clyngor-with-clingo, chardet, biopython, padmet, mpwt, miscoto, menetools, Metage2Metabo
    Running setup.py install for python-libsbml: started
    Running setup.py install for python-libsbml: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pmi3rl57/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/python-libsbml
         cwd: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/
    Complete output (26 lines):
    Using libSBML from: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/libsbml_source
    Using VERSION.txt: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/libsbml_source/VERSION.txt
    Creating: python-libsbml
    Version is: 5.20.0
    building for python: 3.6.9 (default, Mar 10 2023, 16:46:00)
    [GCC 8.4.0]
    running install
    /usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    package init file 'libsbml/__init__.py' not found (or not a regular file)
    running build_ext
    name: _libsbml.cpython-36m-x86_64-linux-gnu.so
    build temp: build/temp.linux-x86_64-3.6
    extension name: _libsbml
    extension dir: build/lib.linux-x86_64-3.6/libsbml/_libsbml.cpython-36m-x86_64-linux-gnu.so
    target_dir_path: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/build/lib.linux-x86_64-3.6/libsbml
    target_lib_path: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/build/lib.linux-x86_64-3.6/libsbml/_libsbml.cpython-36m-x86_64-linux-gnu.so
    suffix: linux-x86_64-3.6
    cwd: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6
    name: _libsbml.cpython-36m-x86_64-linux-gnu.so, tmp: build/temp.linux-x86_64-3.6
    compiling dependencies
    cmake /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/libsbml_dependencies -DCMAKE_BUILD_TYPE=Release -DWITH_STATIC_RUNTIME=ON -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/install_dependencies_linux-x86_64 -DWITH_BZIP2=ON -DWITH_CHECK=OFF -DWITH_EXPAT=ON -DWITH_XERCES=OFF -DWITH_ICONV=OFF -DWITH_LIBXML=OFF
    unable to execute 'cmake': No such file or directory
    error: command 'cmake' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pmi3rl57/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/python-libsbml Check the logs for full command output.
The command '/bin/sh -c curl https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3;    pip install graphviz ete3 networkx;    pip install powergrasp;    pip install Metage2Metabo' returned a non-zero code: 1

**Comment by LiZhihua1982** [comment]
Building wheel for python-libsbml (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-og6wnubb
       cwd: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/
  Complete output (24 lines):
  Using libSBML from: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/libsbml_source
  Using VERSION.txt: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/libsbml_source/VERSION.txt
  Creating: python-libsbml
  Version is: 5.20.0
  building for python: 3.6.9 (default, Mar 10 2023, 16:46:00)
  [GCC 8.4.0]
  running bdist_wheel
  running build
  running build_py
  package init file 'libsbml/__init__.py' not found (or not a regular file)
  running build_ext
  name: _libsbml.cpython-36m-x86_64-linux-gnu.so
  build temp: build/temp.linux-x86_64-3.6
  extension name: _libsbml
  extension dir: build/lib.linux-x86_64-3.6/libsbml/_libsbml.cpython-36m-x86_64-linux-gnu.so
  target_dir_path: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/build/lib.linux-x86_64-3.6/libsbml
  target_lib_path: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/build/lib.linux-x86_64-3.6/libsbml/_libsbml.cpython-36m-x86_64-linux-gnu.so
  suffix: linux-x86_64-3.6
  cwd: /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6
  name: _libsbml.cpython-36m-x86_64-linux-gnu.so, tmp: build/temp.linux-x86_64-3.6
  compiling dependencies
  cmake /tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/libsbml_dependencies -DCMAKE_BUILD_TYPE=Release -DWITH_STATIC_RUNTIME=ON -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-uduyfhq3/python-libsbml_4ef9866f78b6401fafd40149055eeff6/install_dependencies_linux-x86_64 -DWITH_BZIP2=ON -DWITH_CHECK=OFF -DWITH_EXPAT=ON -DWITH_XERCES=OFF -DWITH_ICONV=OFF -DWITH_LIBXML=OFF
  unable to execute 'cmake': No such file or directory
  error: command 'cmake' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-libsbml
  Running setup.py clean for python-libsbml

**Comment by LiZhihua1982** [comment]
Step 9/9 : RUN curl https://bootstrap.pypa.io/get-pip.py | python3;    pip install graphviz ete3 networkx;    pip install powergrasp;    pip install Metage2Metabo
 ---> Running in 5457c9e3ed2d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2518k  100 2518k    0     0  14850      0  0:02:53  0:02:53 --:--:-- 19347
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
/bin/sh: 1: pip: not found
/bin/sh: 1: pip: not found
/bin/sh: 1: pip: not found
The command '/bin/sh -c curl https://bootstrap.pypa.io/get-pip.py | python3;    pip install graphviz ete3 networkx;    pip install powergrasp;    pip install Metage2Metabo' returned a non-zero code: 127

**Comment by LiZhihua1982** [comment]
RUN curl https://bootstrap.pypa.io/get-pip.py | python3.7;\    not python3 is OK

**Comment by ArnaudBelcour** [comment]
Hi @LiZhihua1982,

It is quite difficult to understand what you are trying to do, could you elaborate?

From the traceback, I think you are trying to create a docker from the dockerfile?
If yes, the dockerfile is outdated I have updated it recently: https://github.com/AuReMe/metage2metabo/blob/master/recipes/Dockerfile

The old version of the Dockerfile tries to install Python 3.6 but it is no more compatible with Metage2Metabo. The new version uses Python 3.7 (automatically installed with Ubuntu 20.04) and then installs pip (with the command `apt install python3-pip`). Sadly, i do not have the possibility to test this new version and also I do not have the time.

**Comment by cfrioux** [comment]
Without more information from the author of the issue, I'll close it.
