### ISSUE TITLE
gff file format problem while running m2m recon

### ISSUE THREAD

**Issue by gpchoupichou** [AuReMe/metage2metabo#56]
Hello,
I have a problem running the following command : `m2m recon -g rocks -o rocks_m2m -c 16`
Here is the error message : 

```
######### Running metabolic network reconstruction with Pathway Tools #########
---------- Launching mpwt ----------
No region feature in the GFF file of rocks_bin_231_1, GFF file must have region features.
```
and here is an example of my gff file (obtained with prokka) : 
```
##gff-version 3
##sequence-region c_000000064644 1 1078188
##sequence-region c_000000108022 1 72333
##sequence-region c_000000177873 1 343976
##sequence-region c_000000291080 1 70581
##sequence-region c_000000322418 1 191404
##sequence-region c_000000063443 1 369988
##sequence-region c_000000303010 1 359558
##sequence-region c_000000318942 1 41289
##sequence-region c_000000318773 1 77515
##sequence-region c_000000223418 1 76416
##sequence-region c_000000203556 1 36017
##sequence-region c_000000344245 1 16104
##sequence-region c_000000367754 1 171665
##sequence-region c_000000255903 1 128623
##sequence-region c_000000275449 1 42783
##sequence-region c_000000354647 1 95858
##sequence-region c_000000024095 1 45991
##sequence-region c_000000372217 1 178286
##sequence-region c_000000107681 1 114885
##sequence-region c_000000035827 1 97699
##sequence-region c_000000026743 1 214901
##sequence-region c_000000063357 1 165766
##sequence-region c_000000013580 1 89699
##sequence-region c_000000299742 1 96705
##sequence-region c_000000021783 1 29717
##sequence-region c_000000429765 1 46987
##sequence-region c_000000271007 1 23297
##sequence-region c_000000291991 1 29199
##sequence-region c_000000297940 1 11292
c_000000064644  Prodigal:002006 CDS     137     1213    .       -       0       ID=KJGKFCMM_00001;Name=mreB_1;gene=mreB_1;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:A0A0H3C7V4;locus_tag=KJGKFCMM_00001;product=Cell shape-determining protein MreB
c_000000064644  Prodigal:002006 CDS     1420    2079    .       -       0       ID=KJGKFCMM_00002;inference=ab initio prediction:Prodigal:002006;locus_tag=KJGKFCMM_00002;product=hypothetical protein
c_000000064644  Prodigal:002006 CDS     2445    3521    .       -       0       ID=KJGKFCMM_00003;eC_number=5.2.1.8;Name=surA_1;gene=surA_1;inference=ab initio prediction:Prodigal:002006,protein motif:HAMAP:MF_01183;locus_tag=KJGKFCMM_00003;product=Chaperone SurA
c_000000064644  Prodigal:002006 CDS     3621    7397    .       -       0       ID=KJGKFCMM_00004;eC_number=3.6.4.-;Name=mfd;gene=mfd;inference=ab initio prediction:Prodigal:002006,protein motif:HAMAP:MF_00969;locus_tag=KJGKFCMM_00004;product=Transcription-repair-coupling factor
c_000000064644  Prodigal:002006 CDS     7642    8118    .       -       0       ID=KJGKFCMM_00005;Name=hldE_1;db_xref=COG:COG2870;gene=hldE_1;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:P76658;locus_tag=KJGKFCMM_00005;product=Bifunctional protein HldE
c_000000064644  Prodigal:002006 CDS     8330    9919    .       +       0       ID=KJGKFCMM_00006;eC_number=6.1.1.6;Name=lysU;db_xref=COG:COG1190;gene=lysU;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:P0A8N5;locus_tag=KJGKFCMM_00006;product=Lysine--tRNA ligase%2C heat inducible
c_000000064644  Prodigal:002006 CDS     10088   10498   .       -       0       ID=KJGKFCMM_00007;inference=ab initio prediction:Prodigal:002006;locus_tag=KJGKFCMM_00007;product=hypothetical protein
c_000000064644  Prodigal:002006 CDS     10679   11710   .       -       0       ID=KJGKFCMM_00008;db_xref=COG:COG4447;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:Q8DI95;locus_tag=KJGKFCMM_00008;product=Ycf48-like protein
```
I tried to convert to gbk but the taxonomy was missing and it was still not working. Do you have any idea how I could fix this problem ?
Thanks a lot,
Guillaume

**Comment by ArnaudBelcour** [comment]
Hello,

The error you encounter is that [mpwt](https://github.com/AuReMe/mpwt) (the package used by Metage2Metabo to run Pathway Tools in multiprocess) requires taxonomic information (as Pathway Tools needs them to reconstruct draft metabolic networks). For GFF files, it searches these information in the region feature (where they are stored sometimes). But indeed they are not present in your file.

But it is possible to give the taxonomic information to mpwt with a tsv file. If you create a tsv file in the input folder of m2m called `taxon_id.tsv` (so `rocks/taxon_id.tsv` in your case), you should be able to avoid this issue.

The expected format of this file is one row for each subfolder in `rocks` folder:
| species | taxon_id |
|---------|----------|
|     rocks_bin_231_1    |   ncbi_taxon_id       |
|     other_species    |   ncbi_taxon_id       |

More information are presented in the [readme of mpwt](https://github.com/AuReMe/mpwt#taxon-id-tsv-file). You can obtain the NCBI taxon ID by searching with your organism name on the [NCBI Taxonomy browser](https://www.ncbi.nlm.nih.gov/taxonomy). And when you have found the corresponding organism, you can found the taxon ID on its page, near `Taxonomy ID`. For example, it is 561 for [Escherichia](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=561&lvl=3&lin=f&keep=1&srchmode=1&unlock).
Or you can query the EBI taxonomy at this address: https://www.ebi.ac.uk/ena/data/taxonomy/v1/taxon/scientific-name/
By just giving the taxon name, such as https://www.ebi.ac.uk/ena/data/taxonomy/v1/taxon/scientific-name/Escherichia
And getting the `taxId` parameter.

You can also retrieve the taxon IDs programmatically with the package ete3:

```python

from ete3 import NCBITaxa

ncbi = NCBITaxa()
taxon_name = 'Escherichia'
taxon_translations = ncbi.get_name_translator([taxon_name])
taxon_ids = taxon_translations[taxon_name]
```
Here, `taxon_ids` is a list with the taxon ID (`[561]`).

If you have used Prokka to annotate your data, I will also suggest you to use the `.gbk` files compared to GFF as for some versions of Pathway Tools, the parsing of GFF is less effective than the one of GenBank file. 

Best regards,
Arnaud Belcour.

**Comment by cfrioux** [comment]
Closing the issue now.
