### ISSUE TITLE
Non-caught error in mincom if target sbml is not ok

### ISSUE THREAD

**Issue by cfrioux** [AuReMe/metage2metabo#7]
This might also occur when reading other sbml files along the pipeline (seeds?): has to be checked
Todo: catch the error and exit properly

**Comment by ArnaudBelcour** [comment]
Fix for miscoto in cfrioux/miscoto@0dda18b1071dc8d98163da6e78225acbc86db463.

Need a fix in Menetools.

**Comment by ArnaudBelcour** [comment]
Fix for menetools in cfrioux/Menetools@991caf019d945d3b5036c2dad2905b8d78d7d9e8.

Fix for seeds in f1560256c642a26fe9a15deddcc5203a5228874f.

**Comment by ArnaudBelcour** [comment]
Fix in the AuReMe/metage2metabo@02d92cc5f1c3f6cc8abd441ff5683d5c4a4516df.
